services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: jj
      POSTGRES_PASSWORD: Cambia_Esta_Clave_123!
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  geoserver:
    image: kartoza/geoserver:2.23.2
    container_name: geoserver
    restart: unless-stopped
    environment:
      GEOSERVER_ADMIN_PASSWORD: Admin_1234
    depends_on:
      - postgis
    ports:
      - "8081:8080"   # si lo cambiaste antes a 8081, mantenlo consistente
    volumes:
      - ./data/geoserver_data:/opt/geoserver/data_dir

  web:
    image: nginx:alpine
    container_name: visor_web
    restart: unless-stopped
    depends_on:
      - geoserver
    ports:
      - "8082:80"
    volumes:
      - ./visor-ods:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
